### ISSUE TITLE
config.plist error

### ISSUE THREAD

**Issue by jimyehoo** [jkcoxson/Inspiron-3583-Hackintosh#1]
when I try to open the config.plist file, both the Clover Configurator and XCode give this same error: 

"Clover Configurator was unable read because it isn’t in the correct format.
Please fix the following code before saving: Encountered empty <integer> on line 1099"
and opens up not formated.
Another question is, does the WiFI BT board working or which board did you get to have enable WiFi.
thanks for the hard work.
Any plan to migrate to OpenCore?

**Comment by jkcoxson** [comment]
I haven't updated this in a while, and I have a newer version that works a lot better. I'll upload that when I get time. 
To get the WiFi and Bluetooth to work, you must replace it, but I recommend waiting as right now the market for these chips are trash. I jailbroke an iPhone 5 to use as a wireless adapter until things calm down.
I have no plans to migrate to OpenCore as I don't see the point. Clover is stable, it works, and OpenCore is unstable and will take more research and work.

**Comment by jkcoxson** [comment]
I have redone my Clover config, and I have one that will work now. Just add your own SMBIOS and you should be good to go! https://drive.google.com/file/d/1mEQZWbAZPowJM9hQ3tjvBcm9LSD7wJum/view?usp=sharing

**Comment by jkcoxson** [comment]
This repo has been finished, so this is now done.

**Comment by jkcoxson** [comment]
By the way, I have finally migrated to OpenCore. You had asked about it, and because Big Sur only works well on OpenCore I transfered all the configs.

**Comment by devpedrolira** [comment]
> I have redone my Clover config, and I have one that will work now. Just add your own SMBIOS and you should be good to go! https://drive.google.com/file/d/1mEQZWbAZPowJM9hQ3tjvBcm9LSD7wJum/view?usp=sharing

which smbios should I use for this Dell? MacBookPro15,1?

**Comment by jkcoxson** [comment]
I prefer air for the power savings, but pro has worked for me before.

**Comment by devpedrolira** [comment]
> I prefer air for the power savings, but pro has worked for me before.

Can you send to me the correct? Or I can use MacBookPro15,1?

**Comment by devpedrolira** [comment]
My Dell is Inspiron 3583 with i5 Whyskey lake

**Comment by jkcoxson** [comment]
MacBookAir8,1

**Comment by devpedrolira** [comment]
Thank you so mutch. I made the hackintosh with your EFI, and it’s perfect. The only thing missing is the SMBIOS, but now its complete.

**Comment by jkcoxson** [comment]
You must generate your own SMBIOS because if you ues the same one as me we will both get banned from iCloud.
https://dortania.github.io/OpenCore-Install-Guide/extras/smbios-support.html#macbook-air
https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#generate-a-new-serial

**Comment by devpedrolira** [comment]
Yeah, I know, I dont use ICloud yet, only tested if the system boot up. I Will generate now and test

**Comment by devpedrolira** [comment]
friend, I applied SMBIOS to my config.plist, but it didn’t have any effect, still without identifying which mac is
