### ISSUE TITLE
Help to Hackintosh in 3583

### ISSUE THREAD

**Issue by leandrosouzaa** [jkcoxson/Inspiron-3583-Hackintosh#2]
Hello Jkcox! Can you help me with hack in dell 3583? Tks!!

**Comment by jkcoxson** [comment]
I am not the best at this, so I would recommend getting help on Reddit first. That is where I had the most success getting information. 
I'm having trouble with Github and so the files on here are sorely out of date. I could upload them to Google Drive if you really want the files that I used.
Good luck! You are in for a wild ride!

**Comment by leandrosouzaa** [comment]
Could you send me the image you used? I'm looking for some and I can't find it, if you can send the link with the displayed files I would be grateful! Thank you for your help!

**Comment by jkcoxson** [comment]
I can only supply the Clover that I used, to get the image for MacOS you will need to download it on a Mac or find it elsewhere. Here's my Clover, I'll update github if I can get git to commit and push. 
[EFI.zip](https://github.com/jkcoxson/Inspiron-3583-Hackintosh/files/4435253/EFI.zip)

**Comment by LeandroNobre** [comment]
I put that EFI on meu EFI partition, but my hack start só slowly(Apple loading screen). ;//

**Comment by leandrosouzaa** [comment]
> I put that EFI on meu EFI partition, but my hack start só slowly(Apple loading screen). ;//

Opa Leandro, beleza? Qual imagem utilizou? todas que usei não deu certo! Caso queira entrar em contato de outra maneira, meu email está na minha página de perfil no github.

**Comment by jkcoxson** [comment]
I have made a new clover that will work again. Just add your own SMBIOS and you should be good to go! 
https://drive.google.com/file/d/1mEQZWbAZPowJM9hQ3tjvBcm9LSD7wJum/view?usp=sharing

**Comment by Socorramme** [comment]
Boa tarde, agradeço por estar aqui, estou vendo que vocês estão trocando informações sobre o Dell 3583 e estão fazendo um projeto.
Tenho este modelo, já instalei utilizando uma imagem de um Youtober, porém com uma imagem do modelo 5480, mas o trackpad e o touchpad não funcionou, apesar das configurações serem bem parecidas imaginei que ia funcionar. O Wifi já era esperado.
estou utilizando um adaptador Tenda U3 com driver beta v.3 do Tp link TL725N.

**Comment by leandrosouzaa** [comment]
Olá @Socorramme , obrigado por responder ao tópico. Poderia disponibilizar o link do vídeo?

**Comment by Socorramme** [comment]
https://drive.google.com/file/d/1P48hjbVoVMptHcu289Kub74hmiWI1T5P/view?usp=sharing
https://drive.google.com/file/d/1L9MAwYElpatRCw3GCKr626-0EXphmrY-/view?usp=sharing

[Informações trackpad dell inspiron  3583.txt - Bloco de notas.pdf](https://github.com/jkcoxson/Inspiron-3583-Hackintosh/files/4702972/Informacoes.trackpad.dell.inspiron.3583.txt.-.Bloco.de.notas.pdf)

**Comment by leandrosouzaa** [comment]
Obrigado @Socorramme , tem o link da imagem?

**Comment by Socorramme** [comment]
[Dispositivos PCI do 3583.pdf](https://github.com/jkcoxson/Inspiron-3583-Hackintosh/files/4702992/Dispositivos.PCI.do.3583.pdf)

**Comment by jkcoxson** [comment]
The google Drive link above should have all the clover files that you need to get this working. For the touchpad to work on this machine you must use a DSDT patch. It uses a strange touchpad that requires patching at the Clover level.

**Comment by Socorramme** [comment]
https://drive.google.com/file/d/1S8a_36prbpVHUA_oASBTG8FeUHsmg-_v/view?usp=sharing

**Comment by jkcoxson** [comment]
To be clear, this Github page is sorely out of date and I am working with other people to get it updated. I am not the best at using git.

**Comment by jkcoxson** [comment]
https://drive.google.com/file/d/1mEQZWbAZPowJM9hQ3tjvBcm9LSD7wJum/view?usp=sharing

**Comment by leandrosouzaa** [comment]
> https://drive.google.com/file/d/1S8a_36prbpVHUA_oASBTG8FeUHsmg-_v/view?usp=sharing

Teria o link do vídeo do youtube em?

**Comment by Socorramme** [comment]
posso postar link de vídeo aqui?

**Comment by leandrosouzaa** [comment]
Sim. @Socorramme  poderia me informar se a saída HDMI funciona normalmente?

**Comment by jkcoxson** [comment]
HDMI output should work perfectly once I get the repository up to date. Audio and video.

**Comment by leandrosouzaa** [comment]
Thankss @jkcoxson!! I am go to dowload  the updates

**Comment by jkcoxson** [comment]
Not yet, still pushing. Or trying, lol.

**Comment by leandrosouzaa** [comment]
`git add .` `git commit -m "updates"` and `git push origin master`

**Comment by jkcoxson** [comment]
Got it, thanks for your help!

**Comment by Socorramme** [comment]
> Sim. @Socorramme poderia me informar se a saída HDMI funciona normalmente?

https://www.youtube.com/watch?v=pv0wgXOsj5s

**Comment by leandrosouzaa** [comment]
Obrigado! Seguiu todos os passos que ele fez no vídeo sem mudar nada?

**Comment by Socorramme** [comment]
como eu disse, no vídeo que é para o dell 5480, funcionou perfeitamente, no final ele fala para instalar as kexts de 8ª geração porém no meu caso não funcionou.

**Comment by leandrosouzaa** [comment]
Irei realizar os testes aqui e dou retorno. Muito obrigado!

**Comment by leandrosouzaa** [comment]
@Socorramme , você fez alguma alteração na bios?

**Comment by jkcoxson** [comment]
Were you able to finish this project?

**Comment by Dhroko** [comment]
Hello @jkcoxson!
I put my files on drive to you. I make some changes on, and i have succeed on this hackintosh. I have an i7, and all works, include the Wi-Fi intel with one kext and open natively Wi-Fi monitor on Big Sur. I just have issues with the audio jack, sometimes the audio goes and i have to sleep my Hackintosh to the audio works again. HDMI works fine with audio too. Only the F11 and F12 doesn't work, these two keys just adjust the brightness...and i need these keys to debug, so i put one external keyboard.

https://drive.google.com/file/d/1-jFOtpDs2hAvZj81_VO_Fpy7MdlbpbDd/view?usp=sharing

**Comment by jkcoxson** [comment]
Huh, I had no idea intel wifi was a thing. I am unable to verify that the wifi will work because I replaced mine with a DW1560, but I will change the readme to link the Airportitlwm kext. That's really cool that Intel wifi is a possibility. I have also fixed the HDMI, just haven't pushed yet. For the brightness, I am using karabiner elements because fixing the keyboard function keys are more effort than I am willing to put into it. Sound is difficult, and I haven't gotten around to fixing it yet, as I use my AirPods all the time with it. Congratulations on your hack!

**Comment by Dhroko** [comment]
Thank's, and i really thank you for your contribution with this project, now i can run smoothly my Big Sur. I just have some issues with the openCore, keeps send me log file and i can't fix it, but Mac still running.

**Comment by Dhroko** [comment]
@jkcoxson Let me ask you something, my ethernet (RTL8100) works fine, but if i unplug the cable and plug again, the internet lost the connection, to make work's again i have to reboot or remove the ethernet card on preferences and add again. Have you ever see this before? Another question, how long does your battery last? Sorry for my english, i'm from Brasil.

**Comment by jkcoxson** [comment]
This is unfortunately a known problem with our Ethernet adapter. I have not found a solution to it yet, but I will keep my ears open.

**Comment by Dhroko** [comment]
Another question, how long does your battery take's to drain to 0%?

**Comment by jkcoxson** [comment]
It takes roughly 2-3 hours, depends on what I'm doing. I mostly use mine for college work and visual studio code, all while listening to Spotify. I'm planning on buying Dell's power brick to double that

**Comment by jkcoxson** [comment]
Me having an i3 will also help. You said you had an i7, which will drain quicker.

**Comment by Dhroko** [comment]
Yeah, i have 1-2 hours...i also use to coding with visual studio code and Spotify. Can you send me a link of this power brick...maybe it can help's me.

**Comment by jkcoxson** [comment]
Dell Power Companion PW7015L
About 60 USD on Amazon, 180 from Dell

**Comment by nivaldocavalcanti** [comment]
Olá @Dhroko! Como vai?
Vi que esse EFI que você compartilhou foi criado usando o opencore. 

Poderia compartilhar o tutorial que seguiu para fazer o pendrive com o opencore? 

Segui o tutorial de vídeo indicado por @Socorramme e a instalação do Catalina procedeu sem problemas, mas o Wifi, e algumas teclas como o pipe e o contra-barras não ficaram ok, bem como a tecla Command que ficou localizada no Alt. Não testei o HDMI ainda.

Se eu tiver algum progresso também compartilharei por aqui. Obrigado!

> Hello @jkcoxson!
> I put my files on drive to you. I make some changes on, and i have succeed on this hackintosh. I have an i7, and all works, include the Wi-Fi intel with one kext and open natively Wi-Fi monitor on Big Sur. I just have issues with the audio jack, sometimes the audio goes and i have to sleep my Hackintosh to the audio works again. HDMI works fine with audio too. Only the F11 and F12 doesn't work, these two keys just adjust the brightness...and i need these keys to debug, so i put one external keyboard.
> 
> https://drive.google.com/file/d/1-jFOtpDs2hAvZj81_VO_Fpy7MdlbpbDd/view?usp=sharing

**Comment by nivaldocavalcanti** [comment]
Great news!

Apliquei completamente o EFI que você compartilhou, deu tudo certo! 

Inclusive o Wifi e a atualização para o BigSur procedeu naturalmente.

Obrigado @Dhroko e thank you @jkcoxson for creating this project!

> Olá @Dhroko! Como vai?
> Vi que esse EFI que você compartilhou foi criado usando o opencore.
> 
> Poderia compartilhar o tutorial que seguiu para fazer o pendrive com o opencore?
> 
> Segui o tutorial de vídeo indicado por @Socorramme e a instalação do Catalina procedeu sem problemas, mas o Wifi, e algumas teclas como o pipe e o contra-barras não ficaram ok, bem como a tecla Command que ficou localizada no Alt. Não testei o HDMI ainda.
> 
> Se eu tiver algum progresso também compartilharei por aqui. Obrigado!
> 
> > Hello @jkcoxson!
> > I put my files on drive to you. I make some changes on, and i have succeed on this hackintosh. I have an i7, and all works, include the Wi-Fi intel with one kext and open natively Wi-Fi monitor on Big Sur. I just have issues with the audio jack, sometimes the audio goes and i have to sleep my Hackintosh to the audio works again. HDMI works fine with audio too. Only the F11 and F12 doesn't work, these two keys just adjust the brightness...and i need these keys to debug, so i put one external keyboard.
> > https://drive.google.com/file/d/1-jFOtpDs2hAvZj81_VO_Fpy7MdlbpbDd/view?usp=sharing

**Comment by Dhroko** [comment]
> Great news!
> 
> Apliquei completamente o EFI que você compartilhou, deu tudo certo!
> 
> Inclusive o Wifi e a atualização para o BigSur procedeu naturalmente.
> 
> Obrigado @Dhroko e thank you @jkcoxson for creating this project!
> 
> > Olá @Dhroko! Como vai?
> > Vi que esse EFI que você compartilhou foi criado usando o opencore.
> > Poderia compartilhar o tutorial que seguiu para fazer o pendrive com o opencore?
> > Segui o tutorial de vídeo indicado por @Socorramme e a instalação do Catalina procedeu sem problemas, mas o Wifi, e algumas teclas como o pipe e o contra-barras não ficaram ok, bem como a tecla Command que ficou localizada no Alt. Não testei o HDMI ainda.
> > Se eu tiver algum progresso também compartilharei por aqui. Obrigado!
> > > Hello @jkcoxson!
> > > I put my files on drive to you. I make some changes on, and i have succeed on this hackintosh. I have an i7, and all works, include the Wi-Fi intel with one kext and open natively Wi-Fi monitor on Big Sur. I just have issues with the audio jack, sometimes the audio goes and i have to sleep my Hackintosh to the audio works again. HDMI works fine with audio too. Only the F11 and F12 doesn't work, these two keys just adjust the brightness...and i need these keys to debug, so i put one external keyboard.
> > > https://drive.google.com/file/d/1-jFOtpDs2hAvZj81_VO_Fpy7MdlbpbDd/view?usp=sharing

https://drive.google.com/file/d/14KdeaSsNOE-XzQhzckIsYT441bKWi7ZZ/view?usp=sharing

**Comment by Dhroko** [comment]
Olá @nivaldocavalcanti, desculpa não responder...estava viajando a negócios.
Cara, que bom que deu certo viu...eu fiz algumas modificações no opencore novamente, deixando ele com muitas melhorias, boot mais rápido, removi algumas kexts que estavam em conflito e também atualizei outras. Segue abaixo novo link com os arquivos atualizados e totalmente funcional no Big Sur. Espero que dê tudo certo ai com seu hackintosh e que fique feliz, assim como estou com o meu. Qualquer dúvida estou a disposição para tentar te ajudar. Já adianto para você que caso tenha um mouse gamer, ou um mouse que funcione acima de 125Hz, você terá que mudar em software para que ele funcione a 125Hz...tenho um corsair harpoon rgb, funcionando a 1000Hz, não tinha condição nas animações...travava demais, mudei dentro do software para 125Hz e está muito liso.

https://drive.google.com/file/d/14KdeaSsNOE-XzQhzckIsYT441bKWi7ZZ/view?usp=sharing
 
Minhas especificações:
Processador: i7 8565u
Memória Ram: 16gb
Grafico Onboard: Intel UHD 620 2048gb
Gráfico Offboard: Radeon 520 - Desabilitado por boot-args
SSD 240gb - boot somente com o hackintosh, com som do Big Sur ao iniciar o macos.
Leitor de cartão funcional - Utilizo para descarregar as fotos das máquinas fotográficas.
Wi-Fi Intel totalmente funcional em 2.4ghz - teremos melhorias por vir com funcionalidade do 5ghz


> Great news!
> 
> Apliquei completamente o EFI que você compartilhou, deu tudo certo!
> 
> Inclusive o Wifi e a atualização para o BigSur procedeu naturalmente.
> 
> Obrigado @Dhroko e thank you @jkcoxson for creating this project!
> 
> > Olá @Dhroko! Como vai?
> > Vi que esse EFI que você compartilhou foi criado usando o opencore.
> > Poderia compartilhar o tutorial que seguiu para fazer o pendrive com o opencore?
> > Segui o tutorial de vídeo indicado por @Socorramme e a instalação do Catalina procedeu sem problemas, mas o Wifi, e algumas teclas como o pipe e o contra-barras não ficaram ok, bem como a tecla Command que ficou localizada no Alt. Não testei o HDMI ainda.
> > Se eu tiver algum progresso também compartilharei por aqui. Obrigado!
> > > Hello @jkcoxson!
> > > I put my files on drive to you. I make some changes on, and i have succeed on this hackintosh. I have an i7, and all works, include the Wi-Fi intel with one kext and open natively Wi-Fi monitor on Big Sur. I just have issues with the audio jack, sometimes the audio goes and i have to sleep my Hackintosh to the audio works again. HDMI works fine with audio too. Only the F11 and F12 doesn't work, these two keys just adjust the brightness...and i need these keys to debug, so i put one external keyboard.
> > > https://drive.google.com/file/d/1-jFOtpDs2hAvZj81_VO_Fpy7MdlbpbDd/view?usp=sharing

**Comment by jkcoxson** [comment]
Just keep in mind that this was built for a different hardware stack. Differences in hardware will create issues with booting. @Dhroko why don't you make a pull request?

**Comment by Dhroko** [comment]
@jkcoxson Good idea, doing this now.

> Just keep in mind that this was built for a different hardware stack. Differences in hardware will create issues with booting. @Dhroko why don't you make a pull request?

**Comment by nivaldocavalcanti** [comment]
Muito bom @Dhroko! 

Vou fazer um backup do meu EFI atual e baixar esse que compartilhou para testar aqui... 

Tive mais um progresso essa semana, eu baixei o [OpenCore Configurator](https://mackie100projects.altervista.org/) e através dele eu fiz update dos Kexts, com isso resolveu o meu problema do teclado... aparentemente ainda há algum problema com o vídeo, mas apenas na tela inicial onde a logo do usuário fica bem grande, diferente de quando estava no Catalina, o tamanho parecia mais normal pra mim e também percebi um log do OC apontando falha na resolução inicial, ele tenta ir para 1920x1080 (Full HD) enquanto o monitor do notebook que é 15.6 (HD) só suporta 1366x768. Vou tentar ajustar essa configuração para evitar esse log.

Percebo que temos configurações de hardware um pouco diferentes, optei por uma configuração mais simples, uso este apenas para programação mesmo, veja as minhas:

Processador: i7 8565u - igualmente
Memória Ram: 8gb - **menor**
Grafico Onboard: Intel UHD 620 2048gb - igualmente
Gráfico Offboard: Radeon 520 - **Não tenho** 
SSD 256Gb NVMe M.2 - boot somente com o hackintosh (mas por precaução, habilitei as outras opções de boot que vc havia desabilitado), **sem** som do Big Sur ao iniciar o macos.
Leitor de cartão funcional - igualmente
Wi-Fi Intel totalmente funcional - testei em ambas as frequências aqui e conectou sem problemas. Que parâmetro usou para confirmar que não funciona o 5G por aí?

Também tenho um Desktop (i3 8ª geração 3,6Ghz, 16GB RAM, Intel UHD 630 2GB, SSD 256Gb NVMe M.2 da XPG) com o Catalina instalado, preparando para formatar e instalar o BigSur. O notebook é mais para quebrar o galho em viagens e outros momentos que estou longe do desktop.

Obrigado por compartilhar mais uma vez! 

Manterei contato por aqui sempre que houver algum avanço da minha parte e no que puder ajudar mais alguém também.

> Olá @nivaldocavalcanti, desculpa não responder...estava viajando a negócios.

**Comment by nivaldocavalcanti** [comment]
You're right @jkcoxson! Thanks for your advice!

That's why I will keep a backup of my current EFI before trying any changes in configuration.

Last week I did use Hackintool to download some kexts then when I updated it broke my boot. Fortunately, I have downloaded @Dhroko's EFI in my other hackintosh (Desktop) and I was able to create an USB boot with it and recover my boot (and also, it was a lucky guess, a shot in the dark, cause I didn't know if it would work).

I also recommend everyone who is starting to create a hackintosh to do one change at a time. If anything broke you will know what it was.

> Just keep in mind that this was built for a different hardware stack. Differences in hardware will create issues with booting. @Dhroko why don't you make a pull request?

**Comment by alvess09** [comment]
Hello friends, I also have a dell inspiron laptop
  3583a30P i5 8th intel uhd graphics 620 and, and I'm also in the struggle to do my hackintosh, I installed catalina with the same iso as @Socorramme, but I had the same startup problem, I did the one guided here with the @jkcoxson files, however I only managed to persist and boot from OS only with the opencore, the touchpad worked, the shortcut keys, hdmi working perfectly, the ethernet before putting the opencore was working more after opencore stopped and the Wi-Fi also as expected does not work , if you want I can upload the files I mentioned, is there anything else I can do that I haven't done yet?
if you can help thank you! and I will be happy to contribute as well if possible.

**Comment by jkcoxson** [comment]
This project is in an almost finished state. There isn't much left to do, there are only minor stability things that need to be fixed such as graphics freezes. For your WiFi, there is a new development for Intel based chips that you could try, but I cannot attest to their stability or functionally at all. It was mentioned somewhere up above the driver name. Gg on your new hack!

**Comment by alvess09** [comment]
ok thanks, i will check it out i have a kext for the correction i will
redo it with news give the feedback


Em seg, 18 de jan de 2021 18:28, Jk C <notifications@github.com> escreveu:

**Comment by alvess09** [comment]
hello my friends i managed to do hackingtosh on my laptop with the same files as my friend here i'm using bigsur, works wifi / bluetooth f11 and f12 keys for screen illumination
audio, hdmi, touchpad gestures, webcam but the only thing i saw that doesn't work is the dedicated radeon 520 2gb video card
a hug to everyone and take care

**Comment by jkcoxson** [comment]
You have a different laptop, this is a repository for the Dell Inspiron 3853.

**Comment by alvess09** [comment]
@jkcoxson 
True, but Works on my laptop , i don't had atention on this sorry and ,thanks

**Comment by jkcoxson** [comment]
No harm done, don't even worry about it. Good luck on your hack!

**Comment by agails** [comment]
@jkcoxson  I'm sorry to use this topic but I would like to take some questions with @Dhroko and @nivaldocavalcanti.

@Dhroko e @nivaldocavalcanti desculpem entrar em contato com vocês por aqui mas estou buscando um novo notebook para usar com o Big Sur e cai aqui pois achei a configuração do Dell Inspiron 3000 i15-3583-A40 muito boa e estou pensando em compra-lo, vc's indicam? como está o Hackintosh de vocês? além do wi-fi algo mais não funcionou e tem que ser trocado ou ajustado? estou cotando e pretendo comprar ainda essa semana e gostaria muito do retorno de vc`s, se puderem entrar em contato comigo (meus contatos estão no meu perfil do github) ou se puderem responder aqui mesmo fico imensamente grato. Obrigado e fico no aguardo do retorno de vocês.

**Comment by jkcoxson** [comment]
@agails the laptop works flawlessly with a few caveats. You will either have to replace the Intel WiFi card with a specific compatible one, or you can try your luck with the experimental Intel software driver. You can check specific compatibilities on the readme.
