### ISSUE TITLE
Intel Wifi and SMBIOS

### ISSUE THREAD

**Issue by devpedrolira** [jkcoxson/Inspiron-3583-Hackintosh#4]
Hello, I did the hackintosh with this EFI folder, but I want to use Intel Wifi and when I installed it I generated SMBIOS afterwards and do not recognize it, do I have to generate it before installation? And to install intel wifi I only have to copy the kexts to the efi / oc / kexts folder?

**Comment by devpedrolira** [comment]
I managed to do 100% complete with intel wifi

**Comment by jkcoxson** [comment]
Gg, enjoy your hack 😊
