### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SpaceFlight21** [jkcoxson/Inspiron-3583-Hackintosh#5]
I have Dell Inspiron 3583 and it has a Qualcomm QCA9377 wireless chip, any method that can get Wi-Fi working?

**Comment by jkcoxson** [comment]
Reddit - hackintosh - Kext for Qualcomm QCA61x4A QCA9377 Wi-Fi and Bluetooth driver https://www.reddit.com/r/hackintosh/comments/cslmd0/kext_for_qualcomm_qca61x4a_qca9377_wifi_and/ Quick google found this
